[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
todo_list = "J7qXxzHer5PGZpsQG7nhreGnBcKdHiVRMTj3xUXrELb6"

[programs.localnet]
todo_list = "J7qXxzHer5PGZpsQG7nhreGnBcKdHiVRMTj3xUXrELb6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
